# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-16 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oidc_provider', '0026_client_multiple_response_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='token_refresh_expires_at',
            field=models.DateTimeField(null=True, verbose_name='Expiration Date (Token Refresh)'),
        ),
        migrations.AlterField(
            model_name='responsetype',
            name='value',
            field=models.CharField(choices=[('code', 'code (Authorization Code Flow)'), ('id_token', 'id_token (Implicit Flow)'), ('id_token token', 'id_token token (Implicit Flow)'), ('code token', 'code token (Hybrid Flow)'), ('code id_token', 'code id_token (Hybrid Flow)'), ('code id_token token', 'code id_token token (Hybrid Flow)'), ('client_credentials', 'Client Credential Flow')], max_length=30, unique=True, verbose_name='Response Type Value'),
        ),
    ]
